version: "3.9"

services:
    frontend:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT}:${PORT}"

networks:
    default:
        name: "project-network"
        external: true
