version: "3.9"

services:
    frontend:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PORT: 8080
        environment:
            REGSERVER_REMOTE_BASE_URL: http://localhost:3001
            FILESERVER_REMOTE_BASE_URL: http://localhost:3000
            RPC_NODE_REMOTE_URL: http://localhost:8545
        ports:
            - "8080:8080"

networks:
    default:
        name: "project-network"
        external: true
