version: "3.9"

services:
    frontend:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PORT: ${PORT}
        environment:
            REGSERVER_REMOTE_BASE_URL: http://localhost:3001
            FILESERVER_REMOTE_BASE_URL: http://localhost:3000
            RPC_NODE_REMOTE_URL: http://uchain-rpcnode-1:8545
        ports:
            - "${PORT}:${PORT}"

networks:
    default:
        name: "project-network"
        external: true
