version: "3.9"

services:
    deployer:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - projectnet

networks:
    projectnet:
        external:
            name: projectnet
