version: "3.9"

services:
  bootnode:
    hostname: bootnode
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-bootnode
    command:  
      -nodekey boot.key
      -addr :30303
      -netrestrict="172.16.254.0/24"
    networks:
      - nodenet

  signeralpha:
    hostname: signeralpha
    env_file:
      - .env
    depends_on:
      - bootnode
    build:
      context: .
      dockerfile: Dockerfile-signernode
      args:
        NETWORK_NAME: ${NETWORK_NAME}
        PASSWORD_FILE_NAME: ${ALPHA_PASSWORD_FILE_NAME}
        PRIVATEKEY_FILE_NAME: ${ALPHA_PRIVATEKEY_FILE_NAME}
    command: 
      --datadir . 
      --syncmode "full" 
      --networkid ${NETWORK_ID}
      --miner.gasprice ${MIN_GASPRICE}
      --miner.gaslimit ${GAS_LIMIT}
      --txpool.pricelimit ${TXPOOL_LIMIT}
      --bootnodes "enode://${BOOTNODE_ENODE_ID}@bootnode:30303" 
      --unlock ${PUBLIC_KEY_ALPHA}
      --password ${ALPHA_PASSWORD_FILE_NAME}.txt 
      --mine
      --netrestrict="172.16.254.0/24"
    networks:
      - nodenet
    volumes:
      - chaindata:/node/geth

  signerbeta:
    hostname: signerbeta
    env_file:
      - .env
    depends_on:
      - bootnode
    build:
      context: .
      dockerfile: Dockerfile-signernode
      args:
        NETWORK_NAME: ${NETWORK_NAME}
        PASSWORD_FILE_NAME: ${BETA_PASSWORD_FILE_NAME}
        PRIVATEKEY_FILE_NAME: ${BETA_PRIVATEKEY_FILE_NAME}
    command: 
      --datadir . 
      --syncmode "full" 
      --networkid ${NETWORK_ID}
      --miner.gasprice ${MIN_GASPRICE}
      --miner.gaslimit ${GAS_LIMIT}
      --txpool.pricelimit ${TXPOOL_LIMIT}
      --bootnodes "enode://${BOOTNODE_ENODE_ID}@bootnode:30303" 
      --unlock ${PUBLIC_KEY_BETA}
      --password ${BETA_PASSWORD_FILE_NAME}.txt 
      --mine
      --netrestrict="172.16.254.0/24"
    networks:
      - nodenet

  rpcnode:
    hostname: rpcnode
    env_file:
      - .env
    depends_on:
      - bootnode 
    build:
      context: .
      dockerfile: Dockerfile-rpcnode
      args:
        - NETWORK_NAME=${NETWORK_NAME}
    command:
      --datadir . 
      --syncmode "full" 
      --networkid ${NETWORK_ID} 
      --http 
      --http.addr "0.0.0.0" 
      --http.port ${HTTP_PORT} 
      --http.corsdomain "*" 
      --miner.gasprice ${MIN_GASPRICE}
      --miner.gaslimit ${GAS_LIMIT} 
      --txpool.pricelimit ${TXPOOL_LIMIT} 
      --bootnodes "enode://${BOOTNODE_ENODE_ID}@bootnode:30303"
      --netrestrict="172.16.254.0/24"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/24

volumes:
  chaindata:
