FROM ethereum/client-go:v1.10.26

ARG NETWORK_NAME
ARG NETWORK_ID
ARG PORT
ARG MIN_GASPRICE
ARG GAS_LIMIT
ARG TXPOOL_LIMIT
ARG BOOTNODE_ENODEID
ARG PUBLIC_KEY_BETA

WORKDIR /node

COPY ${NETWORK_NAME}.json .
COPY beta_password.txt .
COPY beta_private_key.txt .

RUN geth --datadir . account import --password beta_password.txt beta_private_key.txt

RUN geth --datadir . init ${NETWORK_NAME}.json

RUN --mount=type=secret,id=beta_password_file,dst=./beta_password_file.txt,required \
    geth --datadir . --syncmode 'full' --networkid ${NETWORK_ID} --port ${PORT} \
    --miner.gasprice ${MIN_GASPRICE} --miner.gaslimit ${GAS_LIMIT} --txpool.pricelimit ${TXPOOL_LIMIT} \
    --bootnodes "enode://${BOOTNODE_ENODEID}@bootnode:${PORT}" --unlock ${PUBLIC_KEY_BETA} \
    --password beta_password.txt --netrestrict="172.16.254.0/24"
# ENTRYPOINT geth --datadir . --syncmode 'full' --networkid ${NETWORK_ID} --port ${PORT} \
#     --miner.gasprice ${MIN_GASPRICE} --miner.gaslimit ${GAS_LIMIT} --txpool.pricelimit ${TXPOOL_LIMIT} \
#     --bootnodes "enode://${BOOTNODE_ENODEID}@bootnode:${PORT}" --unlock ${PUBLIC_KEY_BETA} \
#     --password beta_password.txt --netrestrict="172.16.254.0/24" --mine

ENTRYPOINT geth attach --exec "miner.start()" \\.\pipe\geth.ipc 