FROM ethereum/client-go:v1.10.26

ARG NETWORK_NAME
ARG PASSWORD_FILE_NAME
ARG PRIVATEKEY_FILE_NAME

WORKDIR /node

COPY ${NETWORK_NAME}.json .
COPY ${PASSWORD_FILE_NAME}.txt .
COPY ${PRIVATEKEY_FILE_NAME}.txt .

RUN geth --datadir . account import --password ${PASSWORD_FILE_NAME}.txt ${PRIVATEKEY_FILE_NAME}.txt

RUN geth --datadir . init ${NETWORK_NAME}.json

ENTRYPOINT ["geth"] 