version: "3.9"

services:
    fileserver:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: 3000
        ports:
            - "3000:3000"
        volumes:
            - filestorage:/app/files

volumes:
    filestorage:

networks:
    default:
        name: "project-network"
        external: true
