version: "3.9"

services:
    fileserver:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - filestorage:/app/files

volumes:
    filestorage:

networks:
    default:
        name: "project-network"
        external: true
