version: "3.9"

services:
  fileserver:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command:
      fileServer.js
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - filestorage:/app/files

volumes:
  filestorage: