version: "3.9"

services:
    regserver:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: 3001
            PRIVATE_KEY_FILE: ../run/secrets/wallet_private_key
            RPC_NODE_REMOTE_URL: http://uchain-rpcnode-1:8545
        ports:
            - "3001:3001"
        secrets:
            - wallet_private_key

secrets:
    wallet_private_key:
        file: ./secrets/registrator_private_key.txt

networks:
    default:
        name: "project-network"
        external: true
